### ISSUE TITLE
Type definitions for `onBlur` and `onFocus` are incorrect

### ISSUE THREAD

**Issue by madisonbullard** [stripe/react-stripe-js#105]
https://github.com/stripe/react-stripe-js/blob/master/src/types/index.ts#L18
https://github.com/stripe/react-stripe-js/blob/master/src/types/index.ts#L23

The type definitions do not properly define the argument passed to `onBlur` and `onFocus` props. Both functions are called with a single argument with the following shape:
`{ elementType: 'card' | 'cardNumber' | 'cardExpiry' | 'cardCvc' }`

I might've missed some possible options, but I know that those 4 are valid.

Can we update the types to reflect the function signature?

**Comment by hofman-stripe** [comment]
Thanks for reporting. It looks like the event handler type is also not correctly documented in the base library (e.g. https://github.com/stripe/stripe-js/blob/master/types/stripe-js/elements/card.d.ts)

We'll look into fixing those definitions.

**Comment by madisonbullard** [comment]
The type defs are still incorrect here. Can we re-open in case someone has time to take a look? Thanks!

**Comment by bsharon-stripe** [comment]
Thanks for flagging @madisonbullard, I agree that this should get fixed!

**Comment by christopher-stripe** [comment]
Hi @madisonbullard, this has been fixed in [1.15.1](https://github.com/stripe/stripe-js/releases/tag/v1.15.1).

**Comment by jakub-sarnowski-blinkhealth** [comment]
Wait. This is still not fixed, isn't it?
https://github.com/stripe/react-stripe-js/blob/master/src/types/index.ts#L23

**Comment by jodhman** [comment]
Can confirm in late 2022 that the type definitions are still incorrect.
The onBlur passes down one argument of type `StripeElementType`.

**Comment by martinalong-stripe** [comment]
Should be fixed! Fix will deploy later today
